name:        kb
version:     0.1.0.0
github:      "carp-sushi/kb"
license:     BSD-3-Clause
author:      "carp-sushi"
maintainer:  "105142707+carp-sushi@users.noreply.github.com"
copyright:   "Copyright 2026-present, the original author(s)"
description: Please see the README on GitHub at <https://github.com/carp-sushi/kb#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- configurator
- esqueleto
- fast-logger
- monad-logger
- persistent
- persistent-postgresql
- say
- text
- time
- validation
- wai
- wai-extra
- wai-logger
- warp
- yesod-core
- yesod-persistent

ghc-options:
- -Wall
- -ddump-splices
- -ddump-to-file
- -fwarn-tabs
- -O2

library:
  source-dirs: src

executables:
  kb-migrator:
    main: Main.hs
    source-dirs: migrator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kb
  kb-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kb

tests:
  kb-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kb
    - hspec >= 2.0.0
    - mtl
    - shakespeare
    - yesod-test
